
name: Single Action With Inputs To Echo

on:
  push:
    inputs:
      echo_str:
        description: 'Valor para printar no echo'
        default: 'default'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "${{ github.events.inputs.echo_str }}"
