name: Workflow 1 - Reusing Worflow 1 Generic

on:
  push:
      branches: main

jobs:
  execute-workflow-to-be-skipped-param-java-14:
    uses: pgmfernandes/github-action-reusable-workflow/.github/workflows/workflow-1-to-be-reusable.yml@main
    with:
      java_version: 14
  execute-workflow-param-java-11:
    uses: pgmfernandes/github-action-reusable-workflow/.github/workflows/workflow-1-to-be-reusable.yml@main
    with:
      java_version: 11
